Update/ad-reporting-v2
fivetran/dbt_microsoft_ads pull request #15
Opened 2022-07-05 21:31 UTC by fivetran-sheringuyen

Pull Request
**Are you a current Fivetran customer?** 
Fivetran Employee 

**What change(s) does this PR introduce?** 

**Did you update the CHANGELOG?** 

- [ ] Yes

**Does this PR introduce a breaking change?**

- [ ] Yes (please provide breaking change details below.)
- [ ] No  (please provide an explanation as to how the change is non-breaking below.)

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [ ] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [ ] Yes, Issue/Feature [link bug/feature number here]
- [ ] No 

**How did you test the PR changes?** 

 

- [ ] CircleCi  
- [ ] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [ ] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

2022-07-12 21:10 UTC, fivetran-joemarkiewicz requested changes
@fivetran-sheringuyen thanks so much for putting this PR together! Your updates look mostly good, I just had a few comments inline that should be addressed before we are good to go.
- [x] A few minor README and CHANGELOG updates.
- [ ] A question about including the `match_type` field to the keyword report
- [ ] Question around filtering the url report.
- [ ] Addressing any other inline comments I have from this review.

I also did take a closer look at the url report and the logic you applied makes sense to me! I really appreciated your addition to the DECISIONLOG about the auto tagging nature within Microsoft Ads.

2022-07-12 21:10 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +## 🚨 Breaking Changes
Can you add the PR link to the changelog

2022-07-20 20:35 UTC, fivetran-sheringuyen commented on models/microsoft_ads__keyword_report.sql
> +        keywords.keyword_name,
Ah, I actually think I went into this really gnarly black hole regarding match types (Microsoft has several different kinds) and forgot to switch it to `*_history.match_type`. Good catch, thank you!

2022-07-21 22:38 UTC, fivetran-sheringuyen commented
Hey @fivetran-joemarkiewicz, just updated the PR with your suggested fixes. Let me know if you have any other questions!

2022-07-22 14:10 UTC, fivetran-joemarkiewicz approved these changes
Thanks for making the updates @fivetran-sheringuyen! These look good to go on my end 😄

2022-09-02 03:07 UTC, merged